AWSTemplateFormatVersion: 2010-09-09
Description: >-
  flow-tester

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  FlowTesterTasksQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: flow-tester-tasks-queue
      VisibilityTimeout: 300

  FlowTesterTestRunsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: flow-tester-test-runs-queue
      VisibilityTimeout: 300

  processTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: process-task
      Handler: src/api/tasks.processTaskHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 100
      Description: Process a task from the tasks queue
      Policies:
        - AmazonEC2FullAccess
        - AmazonSQSFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: "arn:aws:iam::746664778706:role/flow-tester-browser-agent-role"
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FlowTesterTasksQueue.Arn
            BatchSize: 1

Outputs:
  QueueUrl:
    Description: URL of the test runs queue
    Value: !Ref FlowTesterTestRunsQueue
    Export:
      Name: !Sub "${AWS::StackName}-QueueUrl"

  QueueArn:
    Description: ARN of the test runs queue
    Value: !GetAtt FlowTesterTestRunsQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-QueueArn"

  QueueUrl:
    Description: URL of the tasks queue
    Value: !Ref FlowTesterTasksQueue
    Export:
      Name: !Sub "${AWS::StackName}-QueueUrl"

  QueueArn:
    Description: ARN of the tasks queue
    Value: !GetAtt FlowTesterTasksQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-QueueArn"